### PR TITLE
Http toolkit#14 copy local+assembly version

### LINKED ISSUE #14: Set copy local to false for references and update AssemblyVersion to 2.4
#### Broken rules:

A. Copy local is set to false for most of the references 
B. `AssemblyVersion` is behind

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #14

### Changelog

- Prevent the copy of redundant assemblies by setting Copy Local to false
- Update `AssemblyVersion` to `2.4.0.0` for the HTTP_Adapter
- Update `AssemblyVersion` to `2.4.0.0` for the HTTP_Engine
- Update `AssemblyVersion` to `2.4.0.0` for the HTTP_oM

### CODE REVIEW

File: HTTP_Adapter/Properties/AssemblyInfo.cs [hunk 1]
```diff
@@ -33,4 +33,4 @@
 // by using the '*' as shown below:
 // [assembly: AssemblyVersion("1.0.*")]
 [assembly: AssemblyVersion("1.0.0.0")]
```
Comment (alelom) [inline HTTP_Adapter/Properties/AssemblyInfo.cs]: I think this should be brought to `2.0.0.0`?

File: HTTP_Engine/Properties/AssemblyInfo.cs [hunk 2]
```diff
@@ -33,4 +33,4 @@
 // by using the '*' as shown below:
 // [assembly: AssemblyVersion("1.0.*")]
 [assembly: AssemblyVersion("1.0.0.0")]
```
Comment (alelom) [inline HTTP_Engine/Properties/AssemblyInfo.cs]: Same?

File: HTTP_oM/Properties/AssemblyInfo.cs [hunk 3]
```diff
@@ -33,4 +33,4 @@
 // by using the '*' as shown below:
 // [assembly: AssemblyVersion("1.0.*")]
 [assembly: AssemblyVersion("1.0.0.0")]
```
Comment (alelom) [inline HTTP_oM/Properties/AssemblyInfo.cs]: Same?
